apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-scos-next-pvc
  namespace: okd-team
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: local
