apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rpm-artifacts-copy 
spec:
  params:
    - description: The rpm artifacts image
      name: image
      type: string
  steps:
    - image: $(params.image)
      name: copy-rpms
      resources: {}
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        rm -rf /workspace/*
        mkdir /workspace/rpms
        cp -irvf /srv/repo/*.rpm /workspace/rpms/
        chmod 0777 /workspace/rpms/
        chmod 0666 /workspace/rpms/*.rpm

  workspaces:
    - mountPath: /workspace
      name: ws
